#services
services:
  backend:
    build: 
      context: ./backend
    ports:
      - 3214:3214
    secrets:
      - db-passwd
    environment:
      - APP_PORT=3214
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWD=/run/secrets/db-passwd

  db:
    image: mariadb:10.7.8-focal
    restart: always
    ports:
      - 3306:3306
    secrets:
      - db-passwd
    volumes:
      - db-data:/var/lib/mysql/
    environment:
      - MARIADB_ROOT_PASSWORD_FILE=/run/secrets/db-passwd
    
  adminer:
    image: adminer:4.8.1-standalone
    restart: always
    depends_on:
      - db
    ports:
      - 8080:8080
    environment:
      ADMINER_DEFAULT_DB_DRIVER: mysql
      ADMINER_DEFAULT_DB_HOST: db
      ADMINER_DESIGN: hydra

#volumes
volumes:
  db-data:      

#secrets      
secrets:
  db-passwd: 
    file: ./database/passwd